### ISSUE TITLE
Fix alignment of heads on left side of about page

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-website#148]
<img width="1392" alt="screen shot 2018-07-03 at 22 53 21" src="https://user-images.githubusercontent.com/438160/42254536-1c8a5e54-7f15-11e8-9a2e-ba46c5d3ef9c.png">
<img width="1392" alt="screen shot 2018-07-03 at 22 53 21" src="https://user-images.githubusercontent.com/438160/42254540-1e70cb9a-7f15-11e8-93c2-a0c0bf7eaca9.png">

**Comment by mirshko** [comment]
Might be closeable now with the TeamMembers below the text? @ricburton
