### ISSUE TITLE
📰 Add media and press kit to the about page

### ISSUE THREAD

**Issue by ricburton** [balance-io/balance-website#150]
I want the /about page to be a place where people can see all of the videos, blog posts, photos and coverage of Balance. That way, anyone who is curious about the company—from journalists to potential employees—can get up to speed.

**Videos**

Inchained - 1.6k followers
https://www.youtube.com/watch?v=4Spq_mgEDVg

**Podcasts**
Blockchain Insider - Largest Fintech podcast network in the world
http://bi.11fs.com/10

Zero Knowledge - Most respected technical crypto podcast
http://www.zeroknowledge.fm/24

**Comment by ricburton** [comment]
https://www.youtube.com/watch?v=FHMcT-nZC8Y
https://www.youtube.com/watch?v=SWrF_Z3PDVg

**Comment by ricburton** [comment]
http://blockcrunch.libsyn.com/can-we-create-a-crypto-bank-richard-burton-balance

**Comment by mirshko** [comment]
Added two new content models 

Outlet
- Name

Press Coverage
- Outlet (Reference)
- Headline
- Date
- Type (Podcast / Video / Article)
- Link (URL)

Populated content models w/ above content.

Will build out scaffolding for _in the news_ section on about us page

Some nice pages
- https://www.mapbox.com/about/press/
- https://www.kickstarter.com/help/brand_assets?ref=press_brand
