### ISSUE TITLE
'Page not found' title is overlapping the nav menu

### ISSUE THREAD

**Issue by davidbanu** [balance-io/balance-website#153]
- The title is overlapping the navigation menu 
![pagenotfoundoverlay](https://user-images.githubusercontent.com/11719931/42960599-f598e0cc-8b94-11e8-88b0-380b4c0f9597.png)
- In mobile view the things get worse...
![pagenotfoundoverlaymobile](https://user-images.githubusercontent.com/11719931/42960600-f5b9ea7e-8b94-11e8-93e5-2e50cc16e550.png)

**Comment by davidbanu** [comment]
The problem with the overlapping was caused by the footer. I found another overlapping of the footer with page components in the Tokens page.
![badfooter](https://user-images.githubusercontent.com/11719931/42969932-7b17bcc6-8bb0-11e8-8d3f-1660ff566165.png)
I've made a commit that will solve the issue for both cases. Tested on all pages to see that everything is alright.

**Comment by mirshko** [comment]
will close in #165
