### ISSUE TITLE
Redirect to 'Page not found' is not working sometimes 

### ISSUE THREAD

**Issue by davidbanu** [balance-io/balance-website#154]
Sometimes redirect to page not found is made twice. Need further investigation...
![brokenredirect](https://user-images.githubusercontent.com/11719931/42960889-db6cda04-8b95-11e8-9348-81aa4adeec0e.png)

**Comment by ricburton** [comment]
That is really bad.

@mikedemarais can help you on this one.

Richard

**Comment by mirshko** [comment]
This is closed with #163
