### ISSUE TITLE
Links to help not working (redirecting to another domain)

### ISSUE THREAD

**Issue by KonstaMerkle** [balance-io/balance-website#177]
When I go here: https://manager.balance.io/ledger and click on help button, it redirects to some weird domain, and shows 404 (not found).

Same for https://manager.balance.io/trezor

**Comment by mirshko** [comment]
@KonstaMerkle Are you being redirected to this url `https://www.scican.com/manager/how-do-i-connect-my-ledger`?

**Comment by KonstaMerkle** [comment]
> @KonstaMerkle Are you being redirected to this url `https://www.scican.com/manager/how-do-i-connect-my-ledger`?

yes

**Comment by mirshko** [comment]
Okay super weird. seems tied to the unavailability of https://support.balance.io/ (the Intercom help center) I'll look into this.

**Comment by mirshko** [comment]
@KonstaMerkle this is fixed but theres still a SSL issue. I will be looking into this next week. closing for now.
