### ISSUE TITLE
Ledger Ethereum application update

### ISSUE THREAD

**Issue by FabriceDautriat** [balance-io/balance-website#183]
Dear Balance-io team.

Ledger is going to release next week a new version of the Ethereum application for Ledger devices.

This application will free more storage on the device. 
To achieve this we removed the ERC20 smart contract list we previously had hard-coded in the device application itself.

As a consequence we modified the ledgerjs codebase to reflect this change.

All details are mentioned here : 
https://github.com/LedgerHQ/ledgerjs/blob/master/docs/migrate_eth_app.md 

Feel free to join our slack (http://slack.ledger.co/) if you need any assistance.

Regards,

Fabrice Dautriat
Coin Integration Product Manager

**Comment by mirshko** [comment]
@FabriceDautriat thanks for the update. its not applicable here afaik. balance-manager might be tho. 

https://github.com/balance-io/balance-manager
